Fix/creator/element
hackathon-21-spring-02/front-end pull request #24
Opened 2021-06-19 15:09 UTC by itt828

- cardの幅を小さくした
- tooltipを右に表示するようにした
  - tooltipにカーソルが重なるとスクロールできなくて辛いため

2021-06-19 15:45 UTC, SSlime-s requested changes
軽くデザイン班の人からの言葉とか入れた :bow:

2021-06-19 15:45 UTC, SSlime-s commented on src/components/CreatorElement.vue
> +    :body-style="{ padding: '5px 5px 5px 5px' }"
padding は 4の倍数のが良くて、さらにデザイン班の人から左右が 12px 上下が 12px にしてほしいって言われてる
加えて、カードの左右に margin を 12px とってほしい :bow: <- これは嘘で、CreatorList から padding を左右に 12px とって :bow:
コードについてなんだけど、`style` を使うのはそんな良くなくて、今回は `body-style` 使わずに `el-card` に `class` で指定してもかわんないはずだからそっちのほうがいいかも

2021-06-19 15:45 UTC, SSlime-s commented on src/components/CreatorElement.vue
> +          height="30"
画像サイズ 48px * 48px にしてほしい :bow:

2021-06-19 15:45 UTC, SSlime-s commented on src/components/CreatorElement.vue
> +          :style="{ 'padding-top': '7px' }"
ここいらないかも あと `style` 直書きはできるだけしないようにしてほしい :bow:

2021-06-19 15:45 UTC, SSlime-s commented on src/components/CreatorElement.vue
> +      <el-col :span="4">
ここらへん `span` 使わずに書き換えてほしい :bow;

2021-06-19 15:45 UTC, SSlime-s commented on src/components/CreatorElement.vue
> +        <el-col :span="20" class="traqid-text">@{{ traqId }} </el-col>
ここも

2021-06-19 15:45 UTC, SSlime-s commented on src/components/CreatorElement.vue
> +      <el-tooltip placement="right" :content="`@${traqId}`" :show-after="100">
ここ画像との `margin` を 12px とってほしい :bow:

2021-06-19 16:21 UTC, itt828 commented on src/components/CreatorElement.vue
> +    :body-style="{ padding: '5px 5px 5px 5px' }"
el-cardのbody-styleのデフォルトがpadding:20pxになっていたので, 変更するためにbody-styleを書くしかない気がします. 
https://element-plus.org/#/jp/component/card#attributes

2021-06-19 16:28 UTC, SSlime-s commented on src/components/CreatorElement.vue
> +    :body-style="{ padding: '5px 5px 5px 5px' }"
:a-: :naruhodo_UD: すまんじゃあお願い :bow: 管理しやすくするためにそこは `padding: 0` だけでもいいかも

2021-06-19 17:08 UTC, SSlime-s commented
↑figma見るとイメージ湧くかも

2021-06-19 19:36 UTC, SSlime-s requested changes
軽く

2021-06-19 19:36 UTC, SSlime-s commented on src/components/CreatorElement.vue
> +    padding: 0 12px;
padding 重複してるかも (特に左)

2021-06-19 19:36 UTC, SSlime-s commented on src/components/CreatorElement.vue
> +  <el-card
めっちゃ申し訳ないんだけど el-menu 使うように実装してもらってもいい？
ちょっとでもめんどくさかったら僕やるから教えて

2021-06-19 19:36 UTC, SSlime-s commented on src/components/CreatorsList.vue
> +  margin: 0px 12px;
ごめん伝え方が悪かった意味的に margin より padding のほうがいいと思う

2021-06-19 19:36 UTC, SSlime-s commented on src/components/CreatorsList.vue
> +  margin: 0px 12px;
(el-menu使うならそもそも padding いらんくなるかも)

2021-06-20 02:31 UTC, SSlime-s approved these changes
:tabun::yosa::kansya:

2021-06-20 02:57 UTC, merged